# Copyright 2022 Lemurian Labs
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE or http://boost.org/LICENSE_1_0.txt)

name: ci_meson

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.hpp"
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
jobs:
  meson-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC 11 Rel (C++20)", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            compiler: gcc-11,
            build_type: RelWithDebInfo,
            cc: "gcc-11", cxx: "g++-11"
          }
        - {
            name: "Linux Clang 12 Rel (C++20)", artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            compiler: clang-12,
            build_type: RelWithDebInfo,
            cc: "clang-12", cxx: "clang++-12"
          }
        - {
            name: "macOS GCC 11 Rel (C++20)", artifact: "macOS.tar.xz",
            os: macos-12,
            compiler: gcc-11,
            build_type: RelWithDebInfo,
            cc: "gcc-11", cxx: "g++-11"
          }
        - {
            name: "Windows MSVC 2022 Rel (C++20)", artifact: "Windows-MSVC.tar.xz",
            os: windows-2022,
            compiler: msvc,
            build_type: RelWithDebInfo,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
    steps:
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - uses: actions/checkout@v3
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        global: true
        name: 'will wray'
        email: 'willwray@gmail.com'
        actor: 'willwray'
        token: '${{ secrets.RW_ORG_REPOS_PAT }}'
    - uses: actions/checkout@v3
      with:
        repository: Lemurian-Labs/lml_namespace
        ref: v1.0
        path: subprojects/lml_namespace
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
    - run: meson setup ${{ matrix.config.compiler }}/
      env:
        CC: ${{ matrix.config.cc }},
        CXX: ${{ matrix.config.cxx }}
    - run: meson test -C ${{ matrix.config.compiler }}/ -v
