# SPDX-FileCopyrightText: 2024 The Lemuriad <opensource@lemuriad.com>
# SPDX-License-Identifier: BSL-1.0
# Repo: https://github.com/lemuriad/parameta

name: ci_meson

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.hpp"
  pull_request:
    paths:
      - "**.cpp"
      - "**.hpp"
jobs:
  meson-build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC-12 Rel c++20, c++17",
            artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            compiler: gcc-12,
            build_type: RelWithDebInfo,
            cc: "gcc-12", cxx: "g++-12"
          }
        - {
            name: "Linux Clang-14 Rel c++20, c++17",
            artifact: "Linux.tar.xz",
            os: ubuntu-22.04,
            compiler: clang-14,
            build_type: RelWithDebInfo,
            cc: "clang-14", cxx: "clang++-14"
          }
        - {
            name: "macOS Clang-14 Rel c++20, c++17",
            artifact: "macOS.tar.xz",
            os: macos-13,
            compiler: clang-14,
            build_type: RelWithDebInfo,
            cc: "clang", cxx: "clang++"
          }
        - {
            name: "Windows MSVC 2022 Rel c++20, c++17",
            artifact: "Windows-MSVC.tar.xz",
            os: windows-2022,
            compiler: msvc,
            build_type: RelWithDebInfo,
            cc: "cl", cxx: "cl",
          }
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1
    - run: meson setup ${{ matrix.config.compiler }}/
      env:
        CC: ${{ matrix.config.cc }},
        CXX: ${{ matrix.config.cxx }}
    - run: meson setup -Dcpp_std=c++17 ${{ matrix.config.compiler }}-c++17/
      env:
        CC: ${{ matrix.config.cc }},
        CXX: ${{ matrix.config.cxx }}
    - run: meson test -C ${{ matrix.config.compiler }}/ -v
    - run: meson test -C ${{ matrix.config.compiler }}-c++17/ -v
